---

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=0
      # localstack has a weird bug where the origin you want allowed needs to be in the middle of a list.
      # It can't be first or last!
      - EXTRA_CORS_ALLOWED_ORIGINS="does-not-matter,http://localhost,also-does-not-matter"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  caddy:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/share/caddy
