---

services:
  ministack:
    image: ministackorg/ministack
    ports:
      - "127.0.0.1:4566:4566"            # MiniStack Gateway
    environment:
      - DEBUG=1
      - LOG_LEVEL=DEBUG
      - MINISTACK_HOST=localhost
      - PERSIST_STATE=1
    volumes:
      - "./.ministack:/tmp/ministack-state"
      - "/var/run/docker.sock:/var/run/docker.sock"
