---

name: Deployment
run-name: Deployment ${{ github.event.deployment_status.state }} on ${{ github.event.deployment.environment }} by ${{ github.actor }}

on:
  deployment_status:

jobs:
  status_update:
    runs-on: ubuntu-latest
    steps:
      - name: Event payload
        run: |
          echo "${{ toJson(github.event) }}"
      - name: Fail job if deployment failed
        if: ${{ github.event.deployment_status.state == 'failure' }}
        run: |
          echo "Deployment failed"
          exit 1

  smoke-test:
    runs-on: ubuntu-latest
    needs: status_update
    if: ${{ github.event.deployment_status.state == 'success' }}
    steps:
      - name: Set URL for main
        if: ${{ github.event.deployment.environment == 'wikiterra/jon-frankel-resume/staging' }}
        run: echo "URL=https://resume-staging.frankel.dev" >> "$GITHUB_ENV"

      - name: Set URL for prod
        if: ${{ github.event.deployment.environment == 'wikiterra/jon-frankel-resume/production' }}
        run: echo "URL=https://resume.frankel.dev" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install npm dependencies
        run: npm install -g pnpm && pnpm install

      - run: pnpx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

