---

name: Deployment
run-name: Deployment ${{ github.event.deployment_status.state }} on ${{ github.event.deployment.environment }} by ${{ github.actor }}

on:
  deployment_status:

jobs:
  status-update:
    name: Status update
    runs-on: ubuntu-latest
    steps:
      - name: Deployment status
        run: |
          echo "${{ toJson(github.event.deployment_status) }}"
      - name: Fail job if deployment failed
        if: ${{ github.event.deployment_status.state == 'failure' }}
        run: |
          echo "Deployment failed"
          exit 1

  set-host:
    name: Set Host
    runs-on: ubuntu-latest
    needs: status-update
    outputs:
      HOSTNAME: ${{ steps.host-output.outputs.HOSTNAME }}
    if: ${{ github.event.deployment_status.state == 'success' }}
    steps:
      - name: Set Host for main
        if: ${{ github.event.deployment.environment == 'wikiterra/jon-frankel-resume/staging' }}
        run: echo "HOSTNAME=resume-staging.frankel.dev" >> "$GITHUB_ENV"

      - name: Set Host for prod
        if: ${{ github.event.deployment.environment == 'wikiterra/jon-frankel-resume/production' }}
        run: echo "HOSTNAME=resume.frankel.dev" >> "$GITHUB_ENV"

      - name: Set Host as output
        id: host-output
        run: echo "HOSTNAME=${{ env.HOSTNAME }}" >> "$GITHUB_OUTPUT"

  purge-cache:
    name: Purge Cloudflare cache
    runs-on: ubuntu-latest
    needs: set-host
    if: ${{ github.event.deployment_status.state == 'success' }}
    environment: ${{ github.event.deployment.environment }}
    env:
      CLOUDFLARE_PURGE_CACHE_TOKEN: ${{ secrets.CLOUDFLARE_PURGE_CACHE_TOKEN }}
      CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
      HOSTNAME: ${{ needs.set-host.outputs.HOSTNAME }}
    steps:
      - name: Purge Cloudflare cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_PURGE_CACHE_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"hosts\": [\"$HOSTNAME\"]}"

  smoke-test:
    name: Smoke test
    runs-on: ubuntu-latest
    needs: [set-host, purge-cache]
    if: ${{ github.event.deployment_status.state == 'success' }}
    env:
      HOSTNAME: ${{ needs.set-host.outputs.HOSTNAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm and install dependencies
        uses: pnpm/action-setup@9b5745cdf0a2e8c2620f0746130f809adb911c19
        with:
          version: 10.6.1
          run_install: true
          cache: true

      - name: Get Playwright version
        id: playwright-version
        run: echo "PLAYWRIGHT_VERSION=$(pnpm list @playwright/test --depth=0 | grep @playwright/test | awk '{print $2}')" >> $GITHUB_ENV

      - name: Cache Playwright Binary
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'

      - name: Install Playwright dependencies
        run: pnpm exec playwright install-deps
        if: steps.playwright-cache.outputs.cache-hit == 'true'

      - name: Run Playwright tests
        run: |
          URL="https://$HOSTNAME"
          make playwright

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
