---

name: Post-deployment
run-name: Deployment ${{ github.event.deployment_status.state }} on ${{ github.event.deployment.environment }} by ${{ github.actor }}

on:
  deployment_status:

jobs:
  # This job runs when a deployment is successful
  post_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Event payload
        run: |
          @echo "${{ toJson(github.event) }}"
      - name: Fail job if deployment failed
        if: ${{ github.event.deployment_status.state != 'success' }}
        run: |
          echo "Deployment failed"
          exit 1
