---

on:
  pull_request:
    branches: ['*']

jobs:
  set_env:
    runs-on: ubuntu-latest
    steps:
      - name: store variable
        run: echo "URL=https://resume-staging.frankel.dev" >> "$GITHUB_ENV"

      - name: read variable
        run: echo $URL
