on:
  push:
    branches:
      - main
      - prod

jobs:
  test_var:
    runs-on: ubuntu-latest
    steps:
      - name: Set URL for main
        if: ${{ github.ref_name == 'main' }}
        run: echo "URL=https://resume-staging.frankel.dev" >> "$GITHUB_ENV" &&

      - name: Set URL for prod
        if: ${{ github.ref_name == 'prod' }}
        run: echo "URL=https://resume.frankel.dev" >> "$GITHUB_ENV" &&

      - name: Show what we got
        run: echo $URL
